package servent.message;

public enum MessageType {
	JOIN, JOIN_RESPONSE, HELLO_NEIGHBOUR, HELLO_REPONSE, RESULT, JOB, REQUEST_TOKEN, TOKEN, RESUME, PAUSE,
	REQUEST_STATUS, STATUS, LEAVING, STEAL_REQUEST, STEAL_RESPONSE
}
